# Project: ch13_3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ch13_3.o count.o
LINKOBJ  = ch13_3.o count.o
LIBS     = -L"C:/Users/GaryWang/Desktop/DevCppPortable/MinGW64/lib" -L"C:/Users/GaryWang/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/GaryWang/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/GaryWang/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/GaryWang/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/GaryWang/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/GaryWang/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/GaryWang/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/GaryWang/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ch13_3.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

ch13_3.o: ch13_3.c
	$(CC) -c ch13_3.c -o ch13_3.o $(CFLAGS)

count.o: count.c
	$(CC) -c count.c -o count.o $(CFLAGS)
